<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>FSharp.Control.Async2</AssemblyName>
    <RootNamespace>Microsoft.FSharp.Control</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Async2Runtime.fs" />
  </ItemGroup>
</Project>
