<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net11.0</TargetFramework><LangVersion>preview</LangVersion><IsTestProject>true</IsTestProject><TreatWarningsAsErrors>false</TreatWarningsAsErrors><GenerateAssemblyInfo>false</GenerateAssemblyInfo><OutputType>Exe</OutputType><UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner><AssemblyName>FSharp.Control.AsyncSeq2.TaskSeq.Tests</AssemblyName></PropertyGroup>
 <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Xunit.Extensions.fs" />
    <Compile Include="TestUtils.fs" />
    <Compile Include="TaskSeq.Append.Tests.fs" />
    <Compile Include="TaskSeq.AsyncExtensions.Tests.fs" />
    <Compile Include="TaskSeq.CancellationToken.Tests.fs" />
    <Compile Include="TaskSeq.Cast.Tests.fs" />
    <Compile Include="TaskSeq.Choose.Tests.fs" />
    <Compile Include="TaskSeq.ChooseV.Tests.fs" />
    <Compile Include="TaskSeq.ChunkBy.Tests.fs" />
    <Compile Include="TaskSeq.ChunkBySize.Tests.fs" />
    <Compile Include="TaskSeq.Collect.Tests.fs" />
    <Compile Include="TaskSeq.CompareWith.Tests.fs" />
    <Compile Include="TaskSeq.Concat.Tests.fs" />
    <Compile Include="TaskSeq.Contains.Tests.fs" />
    <Compile Include="TaskSeq.Delay.Tests.fs" />
    <Compile Include="TaskSeq.Distinct.Tests.fs" />
    <Compile Include="TaskSeq.DistinctUntilChanged.Tests.fs" />
    <Compile Include="TaskSeq.Do.Tests.fs" />
    <Compile Include="TaskSeq.Dynamic.Tests.CE.fs" />
    <Compile Include="TaskSeq.Empty.Tests.fs" />
    <Compile Include="TaskSeq.ExactlyOne.Tests.fs" />
    <Compile Include="TaskSeq.Except.Tests.fs" />
    <Compile Include="TaskSeq.Exists.Tests.fs" />
    <Compile Include="TaskSeq.Filter.Tests.fs" />
    <Compile Include="TaskSeq.Find.Tests.fs" />
    <Compile Include="TaskSeq.FindIndex.Tests.fs" />
    <Compile Include="TaskSeq.FirstLastDefault.Tests.fs" />
    <Compile Include="TaskSeq.Fold.Tests.fs" />
    <Compile Include="TaskSeq.FoldWhile.Tests.fs" />
    <Compile Include="TaskSeq.Forall.Tests.fs" />
    <Compile Include="TaskSeq.GroupBy.Tests.fs" />
    <Compile Include="TaskSeq.Head.Tests.fs" />
    <Compile Include="TaskSeq.Indexed.Tests.fs" />
    <Compile Include="TaskSeq.Init.Tests.fs" />
    <Compile Include="TaskSeq.InsertAt.Tests.fs" />
    <Compile Include="TaskSeq.IsEmpty.fs" />
    <Compile Include="TaskSeq.Issue452.Tests.fs" />
    <Compile Include="TaskSeq.Item.Tests.fs" />
    <Compile Include="TaskSeq.Iter.Tests.fs" />
    <Compile Include="TaskSeq.Last.Tests.fs" />
    <Compile Include="TaskSeq.Length.Tests.fs" />
    <Compile Include="TaskSeq.Let.Tests.fs" />
    <Compile Include="TaskSeq.Map.Tests.fs" />
    <Compile Include="TaskSeq.MapFold.Tests.fs" />
    <Compile Include="TaskSeq.MaxMin.Tests.fs" />
    <Compile Include="TaskSeq.OfXXX.Tests.fs" />
    <Compile Include="TaskSeq.Pairwise.Tests.fs" />
    <Compile Include="TaskSeq.Pick.Tests.fs" />
    <Compile Include="TaskSeq.Realworld.fs" />
    <Compile Include="TaskSeq.Reduce.Tests.fs" />
    <Compile Include="TaskSeq.RemoveAt.Tests.fs" />
    <Compile Include="TaskSeq.Replicate.Tests.fs" />
    <Compile Include="TaskSeq.ReplicateInfinite.Tests.fs" />
    <Compile Include="TaskSeq.Scan.Tests.fs" />
    <Compile Include="TaskSeq.Singleton.Tests.fs" />
    <Compile Include="TaskSeq.Skip.Tests.fs" />
    <Compile Include="TaskSeq.SkipWhile.Tests.fs" />
    <Compile Include="TaskSeq.SplitAt.Tests.fs" />
    <Compile Include="TaskSeq.StateTransitionBug-delayed.Tests.CE.fs" />
    <Compile Include="TaskSeq.StateTransitionBug.Tests.CE.fs" />
    <Compile Include="TaskSeq.SumBy.Tests.fs" />
    <Compile Include="TaskSeq.Tail.Tests.fs" />
    <Compile Include="TaskSeq.Take.Tests.fs" />
    <Compile Include="TaskSeq.TakeWhile.Tests.fs" />
    <Compile Include="TaskSeq.TaskExtensions.Tests.fs" />
    <Compile Include="TaskSeq.Tests.CE.fs" />
    <Compile Include="TaskSeq.ThreadState.Tests.fs" />
    <Compile Include="TaskSeq.ToXXX.Tests.fs" />
    <Compile Include="TaskSeq.Unfold.Tests.fs" />
    <Compile Include="TaskSeq.UpdateAt.Tests.fs" />
    <Compile Include="TaskSeq.Using.Tests.fs" />
    <Compile Include="TaskSeq.Windowed.Tests.fs" />
    <Compile Include="TaskSeq.WithCancellation.Tests.fs" />
    <Compile Include="TaskSeq.Zip.Tests.fs" />
    <Compile Include="TaskSeq.ZipWith.Tests.fs" />
    <Compile Include="Utils.Tests.fs" />
 </ItemGroup>
 <ItemGroup>
   <ProjectReference Include="..\..\src\FSharp.Control.AsyncSeq2\FSharp.Control.AsyncSeq2.fsproj" />
   <PackageReference Include="FSharp.Core" Version="[10.0.100]" ExcludeAssets="all" />
   <PackageReference Include="FsUnit.xUnit" Version="6.0.1" />
   <PackageReference Include="xunit.assert" Version="2.9.3" />
   <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
   <PackageReference Include="xunit.v3.runner.console" Version="3.2.2" />
   <PackageReference Include="xunit.v3.common" Version="3.2.2" />
   <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
   <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" GeneratePathProperty="true" />
 </ItemGroup>
 <ItemGroup>
   <Reference Include="xunit.v3.core" HintPath="$(Pkgxunit_v3_extensibility_core)\lib\netstandard2.0\xunit.v3.core.dll" />
 </ItemGroup>
</Project>